### ISSUE TITLE
Create pypi package

### ISSUE THREAD

**Issue by tvorogme** [toncenter/ton-http-api#1]
There is a problem with the project structure that does not allow making a PyPI package. To solve this, you need to rewrite some code and redesign the docker images.

### Why we need PyPi package?

Other people may follow the [full-node](https://ton.org/docs/#/howto/full-node) guide or make their [own](https://github.com/disintar/ton-k8s) build images. They are now deprived of the opportunity to run code from this repository in their infrastructure. We want to simplify this way up to two commands: `pip install pyton-new` `pyton-new run`

### What actually had to be done?

1. Make a [CLI utility](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) that runs unicorn for pyTON / anTon. As example: `pyton-new run`, `pyton-new run analitics` 
2. Add the ability to load [settings.yaml](https://github.com/toncenter/ton-http-api/blob/master/config/settings.yaml) from the home directory, from the directory in which the user is currently running the script
3. Add the ability to generate settings.yaml from the CLI following the example of `jupyter notebook --generate-config`
3. Make a PyPI package
4. Rewrite Docker images to use PyPi package as shown in [1] (You can do `pip install -e .` in docker for example)

Most likely, our team @disintar will be able to implement this, but the discussion about the correctness of the implementation is open.

**Comment by tvorogme** [comment]
By default, toncenter proxy all requests in nginx through `/api/v2/` [rewriting address](https://github.com/toncenter/ton-http-api/blob/5d1717c135cb3fdc86dd41a2f73dc6368c34032a/infrastructure/nginx/nginx.jinja.conf#L63) , so if you want to start toncenter locally - don't forget to do something with [this](https://github.com/toncenter/ton-http-api/blob/5d1717c135cb3fdc86dd41a2f73dc6368c34032a/pyTON/main.py#L90) 

If you see error page like this: 

![image](https://user-images.githubusercontent.com/19264196/155839621-4110eedd-295e-4629-8cc4-8a783b349d7c.png)

Don't panic, just replace `base_url` in `main.py` :)

**Comment by dungeon-master-666** [comment]
We've added pypi package. Run it by
```
pip install ton-http-api
ton-http-api
```
