### ISSUE TITLE
SASLprep: failed prohibited character check

### ISSUE THREAD

**Issue by romslf** [toncenter/ton-http-api#10]
I get this error on all endpoints, what I am doing wrong ?

`{"ok":false,"error":"SASLprep: failed prohibited character check","code":503}`

**Comment by dungeon-master-666** [comment]
Can you please share the curl request?

**Comment by romslf** [comment]
Sorry but I deleted my VM, I wouldn't be able to do that

**Comment by 663248062** [comment]
I have this problem too, don't know how to fix it?

**Comment by 663248062** [comment]
> Can you please share the curl request?

my mongo_password content is : 123456


{"log":"    return next(self.gen)\n","stream":"stderr","time":"2022-02-15T08:48:47.299282192Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/pool.py\", line 1371, in get_socket\n","stream":"stderr","time":"2022-02-15T08:48:47.299284539Z"}
{"log":"    sock_info = self._get_socket(all_credentials)\n","stream":"stderr","time":"2022-02-15T08:48:47.29928699Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/pool.py\", line 1483, in _get_socket\n","stream":"stderr","time":"2022-02-15T08:48:47.299289365Z"}
{"log":"    sock_info = self.connect(all_credentials)\n","stream":"stderr","time":"2022-02-15T08:48:47.299291821Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/pool.py\", line 1337, in connect\n","stream":"stderr","time":"2022-02-15T08:48:47.299294166Z"}
{"log":"    sock_info.check_auth(all_credentials)\n","stream":"stderr","time":"2022-02-15T08:48:47.29929661Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/pool.py\", line 814, in check_auth\n","stream":"stderr","time":"2022-02-15T08:48:47.299298949Z"}
{"log":"    self.authenticate(credentials)\n","stream":"stderr","time":"2022-02-15T08:48:47.299301394Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/pool.py\", line 831, in authenticate\n","stream":"stderr","time":"2022-02-15T08:48:47.299303709Z"}
{"log":"    auth.authenticate(credentials, self)\n","stream":"stderr","time":"2022-02-15T08:48:47.299308619Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/auth.py\", line 548, in authenticate\n","stream":"stderr","time":"2022-02-15T08:48:47.299311951Z"}
{"log":"    auth_func(credentials, sock_info)\n","stream":"stderr","time":"2022-02-15T08:48:47.299315807Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/auth.py\", line 467, in _authenticate_default\n","stream":"stderr","time":"2022-02-15T08:48:47.299319108Z"}
{"log":"    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-256')\n","stream":"stderr","time":"2022-02-15T08:48:47.299321632Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/auth.py\", line 187, in _authenticate_scram\n","stream":"stderr","time":"2022-02-15T08:48:47.299324084Z"}
{"log":"    data = saslprep(credentials.password).encode(\"utf-8\")\n","stream":"stderr","time":"2022-02-15T08:48:47.299326599Z"}
{"log":"  File \"/usr/local/lib/python3.8/dist-packages/pymongo/saslprep.py\", line 104, in saslprep\n","stream":"stderr","time":"2022-02-15T08:48:47.299329062Z"}
{"log":"    raise ValueError(\n","stream":"stderr","time":"2022-02-15T08:48:47.299331527Z"}
{"log":"ValueError: SASLprep: failed prohibited character check\n","stream":"stderr","time":"2022-02-15T08:48:47.29933383Z"}
{"log":"INFO:     172.24.0.8:51776 - \"GET /favicon.ico HTTP/1.1\" 503 Service Unavailable\n","stream":"stdout","time":"2022-02-15T08:48:47.604205104Z"}

**Comment by dungeon-master-666** [comment]
Thanks for the details. Can you check if your `mongodb_password` file contains \n in the end? If yes, can you try to remove it and rebuild the project? Don't forget to run `docker compose down -v` to clear existing db.

**Comment by 663248062** [comment]
> Thanks for the details. Can you check if your `mongodb_password` file contains \n in the end? If yes, can you try to remove it and rebuild the project? Don't forget to run `docker compose down -v` to clear existing db.

I checked that it does not exist \n, but still report this error.

> {"log":" data = saslprep(credentials.password).encode("utf-8")\n","stream":"stderr","time":"2022-02-15T08:48:47.299326599Z"}
> {"log":" File "/usr/local/lib/python3.8/dist-packages/pymongo/saslprep.py", line 104, in saslprep\n","stream":"stderr","time":"2022-02-15T08:48:47.299329062Z"}
> {"log":" raise ValueError(\n","stream":"stderr","time":"2022-02-15T08:48:47.299331527Z"}
> {"log":"ValueError: SASLprep: failed prohibited character check\n","stream":"stderr","time":"2022-02-15T08:48:47.29933383Z"}

Looking at the words in the error log, I don't know if it is a problem with the generation of the certificate, but I can clearly see the words that the relevant certificate is successfully configured.

This is the certificate generation related log：
```
Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: xxxx.com
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 1
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/xxxx.com.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Attempt to reinstall this existing certificate
2: Renew & replace the certificate (may be subject to CA rate limits)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Keeping the existing certificate
Deploying Certificate to VirtualHost /etc/nginx/nginx.conf
Redirecting all traffic on port 80 to ssl in /etc/nginx/nginx.conf

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully enabled https://xxxx.com
```

**Comment by 663248062** [comment]
I found the reason, it's because I used the vim editor to edit the problem, it will add a newline at the end of the edited file

> By default, VIM will ensure that there must be a newline character at the end of the file (end of line, the specific newline character varies depending on the platform). Because many old and buggy compilers and text processors use EOL as the division between lines, if the last line is directly EOF instead of EOL, the last line will not be processed.

Solution：
`truncate -s -1 private/mongodb_password`

**Comment by dungeon-master-666** [comment]
Good to hear. We can't change how MongoDB docker image reads the password file, but we've added a note in README.md to avoid newline. Closing the issue.
