### ISSUE TITLE
how do I fill in my private lite server'ip in config file?

### ISSUE THREAD

**Issue by airstring** [toncenter/ton-http-api#107]
I read the configuration file: https://ton.org/global-config.json, lite server's  paragraph is shown below. Why is the format of ip not 127.0.0.1, but a number. If i want o point the HTTP API to my own lite server, how do I fill in my private lite server'ip?

`"liteservers": [
    {
      "ip": 84478511,
      "port": 19949,
      "id": {
        "@type": "pub.ed25519",
        "key": "n4VDnSCUuSpjnCyUk9e3QOOd6o0ItSWYbTnW3Wnn8wk="
      }
    },`

**Comment by airstring** [comment]
completed

**Comment by Mountain-AI** [comment]
@airstring lite server run by mytonctrl ?
