### ISSUE TITLE
http api v3

### ISSUE THREAD

**Issue by Denden54** [toncenter/ton-http-api#111]
Hello,

I have an issue with api v3 who is not working for all call I try, with response : 
{"detail":"Not Found"}%

I have no error in logs and api looks running well.

Anyone have an idea ?

Thanks

**Comment by kdimentionaltree** [comment]
Hello, the endpoints /api/v3 will not be released. The API v3 naming was used for [TON Indexer](github.com/toncenter/ton-indexer).
