### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by Soulbadguy54** [toncenter/ton-http-api#21]
Hello, guys. Can somebody helps me with documentation of "how to check transaction status etc" via http api?

I want to use ton for payments, but i found no documentation for this. How should i check status of transaction? How should i better search transaction in blockchain etc?

**Comment by dungeon-master-666** [comment]
Here's some documentation on how to verify transaction: https://docs.ton.org/develop/howto/faq#is-it-possible-to-determine-if-a-transaction-is-100-finalized-is-querying-the-transaction-level-data-sufficient-to-obtain-this-information
