### ISSUE TITLE
ERROR [ton-http-api_nginx 7/9] 'python3\r': No such file or directory

### ISSUE THREAD

**Issue by wolframdeus** [toncenter/ton-http-api#24]
**OS**: Windows 10
**Steps to reproduce**:
1. Clone repository;
2. Generate .env file through running `python ./configure.py`;
3. Try building docker containers through `docker-compose build`
4. Get an error:
```
> [ton-http-api_nginx 7/9] RUN TON_API_CLOUDFLARE_ENABLED=0 TON_API_HTTP_PORT=80 TON_API_INDEX_FOLDER= TON_API_DOMAINS=localhost TON_API_ANALYTICS_ENABLED=0 /usr/src/gen_config.py /usr/src/nginx.jinja.conf /etc/nginx/nginx.conf:      
#14 0.259 /usr/bin/env: 'python3\r': No such file or directory
```

Looks like, the problem is 1 file line endings. In case, `infrastructure/nginx/gen_config.py` line ending is changed to LF, everything works fine.

**Comment by kdimentionaltree** [comment]
We currently didn't tested building service on Windows.

**Comment by wolframdeus** [comment]
Yeah. I am not sure, but the other problem is there is no compatible for Windows OS dll. Currently we have only `.so` which is good for unix, but nothing for Windows.

Just saying for future features.

**Comment by dungeon-master-666** [comment]
It should work on Windows now. If not, please reopen.
