### ISSUE TITLE
getTransactions method limit parameter doesn't work

### ISSUE THREAD

**Issue by kdimentionaltree** [toncenter/ton-http-api#6]
Minimal transactions in liteserver response is 10. That's why service returns 10 transactions even if `limit < 10`. 
This will be fixed to give the expected behavior.

**Comment by dkeysil** [comment]
Requested count = 3
Received 5 transactions

request: https://toncenter.com/api/v2/getBlockTransactions?workchain=0&shard=-9223372036854775808&seqno=23145479&after_lt=25252395000001&after_hash=NhbxPTF4gJmirSc3TROe0WiLFOaMQ6lL5p6a8dBj1Tw%3D&count=3

<details>
<summary>Response</summary>

{"ok":true,"result":{"@type":"blocks.transactions","id":{"@type":"ton.blockIdExt","workchain":0,"shard":"-9223372036854775808","seqno":23145479,"root_hash":"I8IO5R/l4tsvKKfPfr9wgfPEFXs8lHL03qMs3cbfdPc=","file_hash":"0+Gk3wdq458iDebaoFv7rZBwfzHYOa12PJTuG+tID60="},"req_count":3,"incomplete":false,"transactions":[{"@type":"blocks.shortTxId","mode":135,"account":"0:36d0825058cb93cdce2c373e84f2f43eb33d441011b76725cc8e314938021a5a","lt":"25252395000003","hash":"OQ79h2bjxO2aZ4xKUrAeC/4A6wFfDouVAx+ZsKlndFo="},{"@type":"blocks.shortTxId","mode":135,"account":"0:5c1884c0bd0089b9982c0e50d6bd4deac58470b0e84f69cb04f3381b663de415","lt":"25252395000001","hash":"NhbxPTF4gJmirSc3TROe0WiLFOaMQ6lL5p6a8dBj1Tw="},{"@type":"blocks.shortTxId","mode":135,"account":"0:5f00decb7da51881764dc3959cec60609045f6ca1b89e646bde49d492705d77f","lt":"25252395000003","hash":"CAqWUKBqdUHdA7xxxHjSsQvLVU1GtR5lCKeJEZ/shw8="},{"@type":"blocks.shortTxId","mode":135,"account":"0:6420874df8f3a6aa89dcce9ddebdb029bf8812520596122e35976f1e539753d9","lt":"25252395000003","hash":"RsOaorBcci5qHU0WS4Eo6H74Os704zccmZmLtyr2zfY="},{"@type":"blocks.shortTxId","mode":135,"account":"0:77af6ca77d273838d2f42b3c96a0ad05dbd282fc3af10e5485a7399e7fb1427b","lt":"25252395000001","hash":"+TmR1IpRhVtmsb+0mHg/9VYm+HvSEMkTGisJiZnazDw="}],"@extra":"1644082245.0595593:16:0.9154459257702131"}}

</details>

**Comment by dungeon-master-666** [comment]
Fixed in #11
