### ISSUE TITLE
pyTON.worker:report_archival:127

### ISSUE THREAD

**Issue by zhy827827** [toncenter/ton-http-api#73]
main_1  | 2022-12-26 09:35:43.169 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #016 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.235 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #009 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.263 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #007 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.271 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #004 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.289 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #004 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.356 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #010 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.382 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #015 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.420 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #017 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.524 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #000 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.574 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #009 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db
main_1  | 2022-12-26 09:35:43.655 | ERROR    | pyTON.worker:report_archival:127 - TonlibWorker #004 report_archival exception of type BlockNotFound: LITE_SERVER_NOTREADY: seqno not in db

How to solve this issues?

**Comment by dungeon-master-666** [comment]
Fixed in #75. Thanks for reporting.
